# Generated by Django 2.0 on 2022-07-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='laptop.jpg', upload_to='content_img'),
        ),
    ]
